# Notes 

1. Python list does not have to be of same datatypes whereas numpy list HAS TO BE OF SAME DATATYPE.

2. A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used. ndarray stands for 'N-Dimentional Array'

Attributes of an Array

1.   Axes



In [2]:
import numpy as np

# **CREATING ARRAYS**

# Create an Array of 2 zeros 


In [26]:
zero_array = np.zeros(2)
print("zero_array:", zero_array)

zero_array: [0. 0.]


#  Create an Array of 2 ones 


In [27]:
one_array = np.ones(2)
print("one_array:", one_array)

one_array: [1. 1.]


#  Create an empty array with 2 elements


In [65]:
empty_array = np.empty(5)
print("empty_array:", empty_array)

empty_array: [0.  0.5 1.  1.5 2. ]


# Converting Python sequences to NumPy Arrays

> Indented block



In [82]:
a1D = np.array([1, 2, 3, 4])
print("1D Array:", a1D)

a2D = np.array([[1, 2], [3, 4]])
print("2D Array:\n", a2D)

a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", a3D)

1D Array: [1 2 3 4]
2D Array:
 [[1 2]
 [3 4]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#  Manually creating 3 rows and 4 columns and print to display the first row. 

In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a[0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]


# 2D Array creation functions

In [16]:
a = np.eye(3)
print("Array of 3*3 matrix array with randomly arranged 1's & 0's:\n", a)

a = np.eye(3, 5)
print("Array of 3*5 matrix array with randomly arranged 1's & 0's:\n", a)

Array of 3*3 matrix array with randomly arranged 1's & 0's:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array of 3*5 matrix array with randomly arranged 1's & 0's:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Arrange numbers & Linspace


In [63]:
a = np.arange(6)
print("Arrange numbers below 6:", a)
print("print shape:", a.shape)

a = np.arange(2, 10, dtype=float)
print("Arrange numbers btwn 2 & 10 as float:", a)

a = np.arange(2, 3, 0.1)
print("Arrange numbers btwn 2 & 3 with each number diff of 0.1:", a)

Arrange numbers below 6: [0 1 2 3 4 5]
print shape: (6,)
Arrange numbers btwn 2 & 10 as float: [2. 3. 4. 5. 6. 7. 8. 9.]
Arrange numbers btwn 2 & 3 with each number diff of 0.1: [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


# Linspace

In [13]:
a = np.linspace(0,10, num=5)
print("5 Values btwn 0 & 10 ", a)

5 Values btwn 0 & 10  [ 0.   2.5  5.   7.5 10. ]


In [12]:
#Note : The advantage of this creation function is that you guarantee the number of elements 
#and the starting and end point. The previous arange(start, stop, step) will not include the 
#value stop.
a = np.linspace(1., 4., 3)
print("print float values btwn 1. & 4. with difference of 6 :", a)

print float values btwn 1. & 4. with difference of 6 : [1.  2.5 4. ]


# Creating matrix with diag values using command 'diag'. 

In [22]:
a = np.diag([1, 2, 3])
print("Matrix with 1,2,3 in diagonal : \n" , a )

a = np.diag([1, 2, 3], 1)
print("Matrix with 1,2,3 with one shifted diagonal : \n" , a )

a = np.array([[1, 2], [3, 4]])
a1 = np.diag(a)
print("Print only diagonal elements :\n", a1)


Matrix with 1,2,3 in diagonal : 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Matrix with 1,2,3 with one shifted diagonal : 
 [[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]
Print only diagonal elements :
 [1 4]


# Creating matrix using command 'vander' which includes the given set of values.


In [42]:
a = np.vander([1,2,3,4], 4)
print("Vander gives multiples of given values as below :\n", a)

a = np.vander(np.linspace(0,2,4),3)
print("Vander prints 1's, then prints values btwn 0 & 2 and then prints values \nbetween 0 & 4(which is multiple of 2):\n", a)

a = np.linspace(0,2,5)
print("Shows how linspace alone command would print: \n", a)



Vander gives multiples of given values as below :
 [[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
Vander prints 1's, then prints values btwn 0 & 2 and then prints values 
between 0 & 4(which is multiple of 2):
 [[0.         0.         1.        ]
 [0.44444444 0.66666667 1.        ]
 [1.77777778 1.33333333 1.        ]
 [4.         2.         1.        ]]
Shows how linspace alone command would print: 
 [0.  0.5 1.  1.5 2. ]


# Nd ARRAY

In [48]:
a = np.zeros((2,3))
print("Array of 2 rows & 3 columns :\n", a)

a = np.zeros((2,3,2))
print("Array of 2 zero matrix with each 2 rows & 3 columns :\n", a)

Array of 2 rows & 3 columns :
 [[0. 0. 0.]
 [0. 0. 0.]]
Array of 2 zero matrix with each 2 rows & 3 columns :
 [[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


#  Create Arrays of a specific type 

In [6]:
#Types of array possible : int, int0, int16, int32, int64, int8, int_, intc, integer, interp, intersect1d, intp 
#Note : By default takes int64 if mentioned as only int or int0 or int_
a = np.array([127, 128, 129], dtype=np.int)
print("1. Print array of specific dtype :", a)
print("Type of array:", a.dtype)

a = np.array([127, 128, 129], dtype=np.int0)
print("2. Print array of specific dtype :", a)
print("Type of array:", a.dtype)

a = np.array([127, 128, 129], dtype=np.int16)
print("3. Print array of specific dtype :", a)
print("Type of array:", a.dtype)

a = np.array([127, 128, 129], dtype=np.int32)
print("4. Print array of specific dtype :", a)
print("Type of array:", a.dtype)

a = np.array([127, 128, 129], dtype=np.int8)
print("5. Print array of specific dtype :", a)
print("Type of array:", a.dtype)

a = np.array([127, 128, 129], dtype=np.int_)
print("6. Print array of specific dtype :", a)
print("Type of array:", a.dtype)

#Note : intc = int32
a = np.array([127, 128, 129], dtype=np.intc)
print("7. Print array of specific dtype :", a)
print("Type of array:", a.dtype)

#Note : integer dtype is depreciated 
a = np.array([127, 128, 129], dtype=np.integer)
print("8. Print array of specific dtype :", a)
print("Type of array:", a.dtype)

#Note : TypeError: Cannot interpret '<function interp at 0x7f4a07476f80>' as a data type
'''
a = np.array([127, 128, 129], dtype=np.interp)
print("9. Print array of specific dtype :", a)
print("Type of array:", a.dtype)
'''

#Note: TypeError: Cannot interpret '<function intersect1d at 0x7f4a07446b00>' as a data type
'''
a = np.array([127, 128, 129], dtype=np.intersect1d)
print("10. Print array of specific dtype :", a)
print("Type of array:", a.dtype)
'''
#Note : usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: DeprecationWarning: 
#Converting `np.integer` or `np.signedinteger` to a dtype is deprecated. 
#The current result is `np.dtype(np.int_)` which is not strictly correct. 
#Note that the result depends on the system. To ensure stable results use may want to use `np.int64` or `np.int32`.
a = np.array([127, 128, 129], dtype=np.intp)
print("11. Print array of specific dtype :", a)
print("Type of array:", a.dtype)


a = np.array([127, 128, 129], dtype=np.uint32)
print("11. Print array of specific dtype :", a)
print("Type of array:", a.dtype)

a1 = np.array([2, 3, 4], dtype=np.uint32)
b1 = np.array([5, 6, 7], dtype=np.uint32)
c_unsigned32 = a1 - b1
print('unsigned c:', c_unsigned32, c_unsigned32.dtype)
c_signed32 = a1 - b1.astype(np.int32)
#Note : NumPy will assign a new type that satisfies all of the array elements involved in the computation,
#here uint32 and int32 can both be represented in as int64.
print('signed c:', c_signed32, c_signed32.dtype)



1. Print array of specific dtype : [127 128 129]
Type of array: int64
2. Print array of specific dtype : [127 128 129]
Type of array: int64
3. Print array of specific dtype : [127 128 129]
Type of array: int16
4. Print array of specific dtype : [127 128 129]
Type of array: int32
5. Print array of specific dtype : [ 127 -128 -127]
Type of array: int8
6. Print array of specific dtype : [127 128 129]
Type of array: int64
7. Print array of specific dtype : [127 128 129]
Type of array: int32
8. Print array of specific dtype : [127 128 129]
Type of array: int64
11. Print array of specific dtype : [127 128 129]
Type of array: int64
11. Print array of specific dtype : [127 128 129]
Type of array: uint32
unsigned c: [4294967293 4294967293 4294967293] uint32
signed c: [-3 -3 -3] int64


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated. The current result is `np.dtype(np.int_)` which is not strictly correct. Note that the result depends on the system. To ensure stable results use may want to use `np.int64` or `np.int32`.


# How to change an array values to int64 ? 

In [37]:
x = np.ones(2)
x1 = x.int64
print("Default datatype is float64:", x)
print("Changed datatype to int64:", x)

AttributeError: ignored

# Creating Random numbers 

In [53]:
from numpy.random import default_rng 
print("Random numbers of  2 rows & 3 columns of seed 42:\n" , default_rng(42).random((2,3)))
#42 is the seed value 

print("2 Matrix of 3 rows & 2 columns random numbers with seed 42:\n" , default_rng(42).random((4,3,5)))


Random numbers of  2 rows & 3 columns of seed 42:
 [[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]
2 Matrix of 3 rows & 2 columns random numbers with seed 42:
 [[[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
  [0.97562235 0.7611397  0.78606431 0.12811363 0.45038594]
  [0.37079802 0.92676499 0.64386512 0.82276161 0.4434142 ]]

 [[0.22723872 0.55458479 0.06381726 0.82763117 0.6316644 ]
  [0.75808774 0.35452597 0.97069802 0.89312112 0.7783835 ]
  [0.19463871 0.466721   0.04380377 0.15428949 0.68304895]]

 [[0.74476216 0.96750973 0.32582536 0.37045971 0.46955581]
  [0.18947136 0.12992151 0.47570493 0.22690935 0.66981399]
  [0.43715192 0.8326782  0.7002651  0.31236664 0.8322598 ]]

 [[0.80476436 0.38747838 0.2883281  0.6824955  0.13975248]
  [0.1999082  0.00736227 0.78692438 0.66485086 0.70516538]
  [0.78072903 0.45891578 0.5687412  0.139797   0.11453007]]]


# Creating Random numbers using Indicies 

In [60]:
a = np.indices((3,3))
print("Observe that numbers in two different dimensions :\n", a )

a = np.indices((4,4))
print("Observe that numbers in two different dimensions :\n", a )

a = np.indices((3,4))
print("Observe that numbers in two different dimensions :\n", a )

Observe that numbers in two different dimensions :
 [[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
Observe that numbers in two different dimensions :
 [[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]
Observe that numbers in two different dimensions :
 [[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]


# Replicating, Joining, Mutating 





In [79]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:1]
print("b =", b)
b += 2
print("b =", b)
b += 1
print("b =", b)

print("\n")

a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
print("b =", b)
b += 2
print("b =", b)
b += 1
print("b =", b)

print("\n")

a = np.array([1, 2, 3, 4, 5, 6])
b = a[:3]
print("b =", b)
b += 2
print("b =", b)
b += 1
print("b =", b)

b = [1]
b = [3]
b = [4]


b = [1 2]
b = [3 4]
b = [4 5]


b = [1 2 3]
b = [3 4 5]
b = [4 5 6]


In [83]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

# create some fake data
x = y = np.arange(-4.0, 4.0, 0.02)
# here are the x,y and respective z values
X, Y = np.meshgrid(x, y)
Z = np.sinc(np.sqrt(X*X+Y*Y))
# this is the value to use for the color
V = np.sin(Y)

# create the figure, add a 3d axis, set the viewing angle
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.view_init(45,60)

# here we create the surface plot, but pass V through a colormap
# to create a different color for each patch
ax.plot_surface(X, Y, Z, facecolors=cm.Oranges(V))